from app.main import app
from app import SEO_KEY_BASE_PATTERN, ARTIST_ID_PATTERN, LANGUAGE_PATTERN, SEARCH_QUERY_PATTERN

__all__ = [
    "app",
    "SEO_KEY_BASE_PATTERN",
    "ARTIST_ID_PATTERN",
    "LANGUAGE_PATTERN",
    "SEARCH_QUERY_PATTERN",
]
